#Convert the one datatype into another datatype
#Only aplicable for int, float, string, complex, boolean
a=int(10)
b=int(8.3)
c=int("10")
print(a,type(a))
print(b,type(b))
print(c,type(c))
print()
x=float(8.3)
y=float(10)
z=float("10")
print(x,type(x))
print(y,type(y))
print(z,type(z))
print()
s1=str("10")
s2=str(10)
s3=str(8.3)
print(s1,type(s1))
print(s2,type(s2))
print(s3,type(s3))